### PR TITLE
removed LOAD, using v2.7 instead

### PR DESCRIPTION
**Pull request by invemichele**

### CODE REVIEW

**Comment by maxbonomi** [comment]
Thanks! Did you also remove the LOAD directive from the PLUMED input files in your zip archive?

**Comment by invemichele** [comment]
yes!

**Comment by maxbonomi** [comment]
Cool! Merged ;-)

**Comment by maxbonomi** [comment]
do you think you can remove LOAD also from the PLUMED input files in plumID:20.022?

**Comment by invemichele** [comment]
No, that uses a different bias class, which is still not ready for a stable release. But I will send a pull request with it to add it to the master branch when it will be separated from v2.7
Some LOAD were removed from plumID:20.004 and plumID:20.025, but they do not compile anyway, because of pytorch...

**Comment by maxbonomi** [comment]
Got it, thanks ;-)

**Pull request merged**
