### PR TITLE
Remove /test-site/ from badge URLs

### PR DESCRIPTION
**Pull request by spiwokv**
URLs in badge links were modified to remove "/test-site".

### CODE REVIEW

**Comment by spiwokv** [comment]
and I removed <font> and replaced it by CSS

**Comment by spiwokv** [comment]
and I removed &lt; font &gt; and replaced it by CSS

**Comment by GiovanniBussi** [comment]
I think I fixed this already in 03afc541475bcc17695dad2436d6efade0d005ea

Thanks anyway!

**Comment by spiwokv** [comment]
Great, maybe you can do the &gt;font&lt; removal, but this is just an HTML purism.

**Comment by spiwokv** [comment]
&lt;font&gt;

**Comment by GiovanniBussi** [comment]
Mm I am afraid I am not able..

**Comment by spiwokv** [comment]
It is https://github.com/plumed-nest/plumed-nest/pull/62/commits/0d1dcbe259f1f76f8f30efebf9141402ba645eed on  _layouts/default.html and assets/css/style.scss, without modification of  _sass/jekyll-theme-cayman-green.scss, but not a big issue.

**Pull request closed without merging**
