### PR TITLE
Table js

### PR DESCRIPTION
**Pull request by a-cesari**
I removed the filters as agreed. 
The width should also be fine now. 
There is still column ordering that can be easily de-activated if you prefer.

### CODE REVIEW

**Comment by maxbonomi** [comment]
Can we see this in the test site before merging?

**Comment by GiovanniBussi** [comment]
@maxbonomi you should push Andrea’s branch to test branch

**Comment by maxbonomi** [comment]
I see just the option merge to master :-(
I am not good with git

**Comment by GiovanniBussi** [comment]
Done right now. For next time:
````
git remote add a-cesari git://github.com/a-cesari/plumed-nest.git  # only needed once
git push -f origin a-cesari/table-js:test
````

**Comment by GiovanniBussi** [comment]
To me it looks ok. The only problem that I see is that using shortened names and keywords is suboptimal. Perhaps we could put in the table the full text, if there is a way to make column width fixed, so that when the text is too long they are spread on multiple lines?

Additionally, we might allow people to download the table in csv format (that can be opened also with Excel), perhaps including more fields there.

**Comment by maxbonomi** [comment]
I like it A LOT, but I think we should polish it a bit more:
- the table is not spanning the whole width of the page (look at the search field how it extends to the  right)
- we should leave a bit of space between the line with "Search" and "Show XX entries" and the beginning of the table
- I would prefer to use a shortened version of some fields. I would not want a very long title to occupy 4 or 5 lines

**Comment by GiovanniBussi** [comment]
I just pushed a version with full titles. The point of having the shortened versions is that the latest words cannot be searched... maybe there is a way to include all the words in the table (so that they can be searched) and use javascript to display only the first 15 characters or so

**Comment by GiovanniBussi** [comment]
I actually like the version with full texts!

**Comment by maxbonomi** [comment]
Actually it is better than expected, and you are right about searching keywords with short “titles”
ok, happy with this version, just some minor typographical stuff

**Comment by GiovanniBussi** [comment]
I would suggest to write contributor as "Bussi G." so that 1. it is shorter and 2. it gets sorted correctly. I think it should be easy to do with Jekyll

**Comment by carlocamilloni** [comment]
I like it a lot! Only issue on mobile is an overlap between the search field and the table



Sent from my iPhone

> Il giorno 26 apr 2019, alle ore 13:20, Massimiliano Bonomi <notifications@github.com> ha scritto:
> 
> Actually it is better than expected, and you are right about searching keywords with short “titles”
> ok, happy with this version, just some minor typographical stuff
> 
>

**Comment by maxbonomi** [comment]
All of them “Bussi G.” ???
;-)

**Comment by GiovanniBussi** [comment]
Of course! That's just to make the table nicer. Other surnames are too long :-)

**Comment by maxbonomi** [comment]
I would merge it now and later fix the space between search field and table
it is really cool! Thanks @a-cesari

**Comment by a-cesari** [comment]
Ok..
I will try to do a nicer search box during the weekend and also fix the
space.
Actually on my local version there was the space which is then not
appearing on the online version. I will have to understand why.

Il ven 26 apr 2019, 21:19 Massimiliano Bonomi <notifications@github.com> ha
scritto:

**Comment by a-cesari** [comment]
Hi all,
I pushed a new version with nicer search box fixing also some typographical stuff as Max suggested.
I also added 3 buttons to copy the table to the clipboard, export in excel or pdf (as Giovanni suggested). The style of the button of course can be improved but I think is ok for now. 
The best aesthetic result is obtained with chrome, although also with Safari and Firefox is acceptable. Some additional work will be required to obtain the same result since some components behave differently on different browsers. I attach here what I see in my Chrome browser. 
Let me know. 

image

**Comment by maxbonomi** [comment]
ohhh, I might have a reason for switching to Chrome now

**Comment by a-cesari** [comment]
I was sure you were using Safari :)

**Comment by maxbonomi** [comment]
best browser, it just works

**Comment by GiovanniBussi** [comment]
Great @a-cesari ! I'll merge it and also add as separate commits my small changes (no shortcuts and Surname N.).

**Comment by maxbonomi** [comment]
Great! Looking forward to coming back from my Saturday Zumba class and play with it

**Comment by carlocamilloni** [comment]
Great job! Thanks!

Sent from my iPhone

**Comment by carlocamilloni** [comment]
😂 greetings from the riviera romagnola!

Sent from my iPhone

**Comment by maxbonomi** [comment]
This sounds like more fun

**Comment by maxbonomi** [comment]
On my chrome looks worse and identical to Safari :-(
Screen Shot 2019-04-27 at 11 58 51

**Comment by GiovanniBussi** [comment]
I have the same problem
image

@a-cesari maybe I made some mistake in merging?

**Comment by a-cesari** [comment]
Yes I think there should be something with Jekyll setup and it is not reading the additional style.scss file present insets/css

**Comment by a-cesari** [comment]
Sorry: present in assets/css

**Comment by maxbonomi** [comment]
There is a yml file somewhere with the list of files to include

**Comment by GiovanniBussi** [comment]
Mm [very bad](https://www.plumed-nest.org/test-site/browse.html)

I am trying on test branch. I tried to revert one of the changes I was not sure about. Let's see

**Comment by GiovanniBussi** [comment]
It works now I'll merge to master

**Comment by a-cesari** [comment]
Ok. Which was the problem then?

**Comment by GiovanniBussi** [comment]
The `assets` directory was not copied. [This](https://github.com/plumed-nest/plumed-nest/commit/a2c948fa3e43d9aeb19c5d796c59e8613eecc9bf) was the correct fix.

**Comment by a-cesari** [comment]
Ok I found it. In travis yml config.

**Comment by GiovanniBussi** [comment]
@a-cesari sorry I thought this was closed.. should I merge the next commit?

**Comment by a-cesari** [comment]
Yes it should contain the Safari fix for @maxbonomi

**Comment by GiovanniBussi** [comment]
ok I merged it. I close this pull request now. Thanks @a-cesari this was very useful and totally out of reach (at least for me)

**Pull request closed without merging**
