### PR TITLE
Testing datatable

### PR DESCRIPTION
**Pull request by a-cesari**
quick datatable test.

### CODE REVIEW

**Comment by maxbonomi** [comment]
Stupid question.
I thought Github pages were static and we were not allowed to run javascripts.

Can we test this commit in our test website?

Max

**Comment by GiovanniBussi** [comment]
Yes you can just fetch Andrea's branch locally and force push it to test
branch

**Comment by a-cesari** [comment]
I think Javascript is allowed. 

Up to my knowledge what is not allowed are server side operations (e.g. using php).

**Comment by maxbonomi** [comment]
Fantastic

**Comment by maxbonomi** [comment]
Will try to do it later today.
But if somebody else has time, please go ahead!

**Comment by GiovanniBussi** [comment]
Done now (it shows as merged since Andrea was asking to merge on test branch)

**Pull request merged**
