### PR TITLE
Table js

### PR DESCRIPTION
**Pull request by GiovanniBussi**
Same as #41 but rebased on current master. @a-cesari

Now rendered one the [test site](https://www.plumed-nest.org/test-site/browse.html).

I think it is pretty cool! A few comments:
- The header is doubled. @a-cesari you explicitly added it twice, was it a mistake?
- The keywords should be probably stored differently, otherwise sorting using that column makes no sense.

Anyway, it's really cool, also the search box seems very useful (it searches all fields)

### CODE REVIEW

**Comment by maxbonomi** [comment]
Beautiful Andrea!

**Comment by GiovanniBussi** [comment]
Selection is really useful (to get all projects from the same contributor or category)!!

There is still some issue:
- Selection does not work correctly for plumID (I don't understand why)
- Selection does not work correctly for keywords (here I think the problem is that we put multiple keys as comma separated... it there a better way?
- Table is too large and does not fit

**Comment by a-cesari** [comment]
First two points should be easy to fix.
Regarding table width I think there is the same problem with the static
table. It's just too large.
Anyway it should scroll horizontally. At least in my browser is scrolling.

Il mer 24 apr 2019, 10:37 Giovanni <notifications@github.com> ha scritto:

**Comment by maxbonomi** [comment]
I would remove the menu in the second line for these entries:
plumID
Name
Keywords

as they do not make much sense to me and contribute to the width of the table

**Comment by maxbonomi** [comment]
Also, entries should be in reverse plumID order

**Comment by maxbonomi** [comment]
Ah, there is a sort button, fantastic

**Comment by a-cesari** [comment]
I agree.

Il mer 24 apr 2019, 11:13 Massimiliano Bonomi <notifications@github.com> ha
scritto:

**Comment by maxbonomi** [comment]
unless we split a list of keywords in individual ones and search based on those

**Comment by maxbonomi** [comment]
Regarding the table width, I think it would be nice to have all the information without scrolling, at least on a desktop computer. With the old table, no scrolling was required ;-)

**Comment by a-cesari** [comment]
I was looking at it right now. There is something strange between the page css and the DataTable one.

**Comment by maxbonomi** [comment]
actually with the search field I don't really see the need of also the menu in the second line

**Comment by carlocamilloni** [comment]
I agree the table is great, agree with Max to remove the menu in the second line. On mobile it doesn’t look great but maybe sorting out the size on desktop will also improve the mobile 

Sent from my iPhone

**Pull request merged**
