### PR TITLE
Nest badge with modals

### PR DESCRIPTION
**Pull request by spiwokv**
Here is a Nest badge with a modal showing the Markdown and HTML code, so proud author of a nest egg can copy and paste the code to include the badge on GitHub or a web. Sorry again for my previous wrong pull attempt.

### CODE REVIEW

**Comment by spiwokv** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data/./Trajectories/EDS-flattening-enm/flatten-dihed-mean-mean2-cleft-mean-mean2/lm_adaptive/gatp-enm-12site_FEStart_eq175ns.range1_init0_lm01/gatp-enm-12site_FEStart_eq175ns.range1_init0_lm01.10ps.run.20000000.plumed.dat'

**Comment by maxbonomi** [comment]
This path is not in the master version of plumed-nest.
Where did you get this error?

**Comment by spiwokv** [comment]
It looks like my GitHub ignorance continues.

spiwokv wants to merge 3 commits into plumed-nest:test from spiwokv:test

is wrong?

**Comment by maxbonomi** [comment]
The zip file of that egg was modified along with nest.yml in the master branch.
So in order to pass the tests in your branch you have first to merge master in your branch.

**Comment by spiwokv** [comment]
Many thanks!!!

**Pull request merged**
