### PR TITLE
add bib and ris

### PR DESCRIPTION
**Pull request by spiwokv**
I have just added a BIB and RIS bibliography files for easier citing of Nature Methods paper. Thanks to Petra Rubesova for testing RIS files. Unlike previous pull request, this is file-free (javascript based, no need to update .travis.yml). You can try here:

https://spiwokv.github.io/plumed-nest/cite.html

### CODE REVIEW

**Comment by spiwokv** [comment]
Dear colleaguaes, can you please restart the Travis build? It looks like the error is caused by  some temporarily disabled URL, rather than by some true error. Thanks

**Comment by maxbonomi** [comment]
Hi I haven’t had the time to look at your commit and I have not merged it yet.
I think I will not have time until next week. Sorry.

**Comment by spiwokv** [comment]
No problem, we have also grant report deadlines now :-)

**Comment by spiwokv** [comment]
It looks like it passes Travis-CI.

**Comment by spiwokv** [comment]
Thanks!

**Pull request merged**
