### PR TITLE
AGC submission attempt

### PR DESCRIPTION
**Pull request by tonigi**

### CODE REVIEW

**Comment by maxbonomi** [comment]
I merged. All the scripts are failing, even on the master version. I am not sure it make sense to have these examples if there is code needed to make all of them working. What do you guys think?

**Comment by GiovanniBussi** [comment]
I am happy with all choices, but personally I would vote for keeping them. I think it is a good way to advertise features.

People navigating the nest and interested in this will need to install a special version, so it is important that instructions contain this information. This is not much different from features available in master only: also in that case people would have to install a development branch.

**Comment by tonigi** [comment]
Ouch. I am making a zip without input files (or, better, providing a comment-only one for plumed-nest).

**Comment by carlocamilloni** [comment]
I agree with Giovanni, I think the only issue is to mention it correctly in the PLUMED-version field (like v2.5-giorgino)
Now 2.5.1 is misleading.

C

**Pull request merged**
